### ISSUE TITLE
Make `moargration` work with AR 4

### ISSUE THREAD

**Issue by owenthereal** [pedro/moargration#1]
Miss this one during AR 3 upgrade for API. But we'd need this for AR 4 :).

**Comment by mikehale** [comment]
Yeah I think it's been okay because we didn't actually have any migrations that relied on this gem since the AR3 upgrade, but we have at least one in the list of PRs now.

**Comment by pedro** [comment]
Hey folks,

Testing this briefly I think Moargration is not needed with AR4. It apparently skips nil attributes both on INSERT and UPDATE, just like `Sequel::Model`:

> D, [2015-09-21T14:59:52.602721 #46046] DEBUG -- :   SQL (0.4ms)  INSERT INTO "apps" ("owner_id", "name", "stack", "uuid", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["owner_id", 19], ["name", "omg-works"], ["stack", "cedar"], ["uuid", "099b3a10-14e8-4342-90b0-84eff4c3c518"], ["created_at", "2015-09-21 14:59:52.600948"], ["updated_at", "2015-09-21 14:59:52.600948"]]
> 
> D, [2015-09-21T15:08:20.157202 #46046] DEBUG -- :   SQL (0.4ms)  UPDATE "apps" SET "log_token" = $1, "updated_at" = $2 WHERE "apps"."id" = $3  [["log_token", "foo"], ["updated_at", "2015-09-21 15:08:20.155879"], ["id", 5]]

If you do try to update a column that was removed since the process booted, AR raises a pretty nice/descriptive error from `pg`:

> E, [2015-09-21T15:09:09.389549 #46046] ERROR -- : PG::UndefinedColumn: ERROR:  column "last_git" of relation "apps" does not exist

So I'd advise to proceed normally without Moargration: first change all processes to stop reading/writing to that column, then run the migration to nuke it. I'll update the readme to cover this.

Thanks!

**Comment by pedro** [comment]
Ugh, @rwz found out that despite not using cached columns on INSERT/UPDATE, AR4 can use them on some joins. It seems like we'll still need to filter columns after all...

**Comment by owenthereal** [comment]
@pedro How can we help to make moargration work again for AR4?

**Comment by pedro** [comment]
@jingweno tested and it just works! AR4 still has `columns` defined on AR::Base, and the override in moargration still applies.
